/**
 * tests/integration/tokenizer.test.ts — conformance suite for
 * server/tokenizer.ts (epic-token-view story S3).
 *
 * Runs under vitest.server.config.ts (node env) per AC-ERR-3 — never the
 * jsdom tests/unit suite.
 *
 * Fixture provenance: `tests/fixtures/qwen3-1.7b-vocab.json.gz` and
 * `tests/fixtures/qwen3-1.7b-goldens.json` are GENUINE captures, not
 * hand-built. The vocab fixture is a byte-identical snapshot of the
 * `tokenizer.ggml.*` fields from a live `qwen3:1.7b` `POST /show`
 * (verbose) response (151936 tokens, 151387 merges); the golden fixture's
 * `tokenIds` were produced by `@huggingface/transformers`'
 * `AutoTokenizer.from_pretrained("Qwen/Qwen3-1.7B")` against that same
 * model's real `tokenizer.json`, via `scripts/capture-vocab-fixture.mjs`.
 * (An earlier revision of this suite ran against a hand-constructed
 * 297-token stand-in fixture, built when no live host or reference
 * tokenizer was reachable from this environment — that constraint no
 * longer holds here, so the fixtures were recaptured for real; see
 * AC-DEP-2's conformance test in capture-vocab-fixture.test.ts.)
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import fc from "fast-check";
import { gunzipSync } from "node:zlib";
import { readFileSync } from "node:fs";
import {
  tokenize,
  tokenizeWithVocab,
  decodeTokenIds,
  loadVocab,
  bpeMerge,
  __resetVocabCacheForTests,
  __preTokenizeForTests,
  VocabUnavailableError,
  type VocabTable,
} from "../../server/tokenizer.js";
import { checkLiveGate, tokenizerLiveOllamaUrl } from "./tokenizer-live-gate.js";

const VOCAB_JSON = gunzipSync(readFileSync("tests/fixtures/qwen3-1.7b-vocab.json.gz")).toString("utf-8");
const GOLDENS = JSON.parse(readFileSync("tests/fixtures/qwen3-1.7b-goldens.json", "utf-8")) as Record<string, number[]>;
const MODEL = "qwen3:1.7b";
const BASE_URL = "http://fake-ollama/api";

/** glossary "fixture set" — see acceptance-criteria.md's Terminology section. */
const FIXTURE_SET = Object.keys(GOLDENS);

/**
 * A SEPARATE, broader golden fixture — not the glossary "fixture set"
 * above, and not consumed by AC-TOK-1/AC-TOK-2/AC-TOK-7/AC-DEP-2. Kept
 * distinct deliberately: AC-TOK-2's per-index `decodeTokenIds` check
 * assumes none of FIXTURE_SET's strings contain a multi-byte character
 * that a token boundary splits, and AC-TOK-1's live-gated oracle test
 * sends FIXTURE_SET strings through Ollama's raw-mode `/generate` —
 * neither assumption has been verified for special-token literals,
 * digit-heavy text, or multi-byte scripts, so this fixture's strings stay
 * out of FIXTURE_SET rather than risk quietly invalidating those two
 * checks. `tokenIds` here were produced by the same reference tokenizer
 * path as the golden fixture (`AutoTokenizer.from_pretrained` over the
 * real `Qwen/Qwen3-1.7B` tokenizer.json), generated by hand for this gap
 * (see this suite's history) rather than by
 * `scripts/capture-vocab-fixture.mjs`, whose committed-output contract is
 * scoped to the glossary "fixture set" (AC-DEP-2).
 */
const CONFORMANCE_GOLDENS = JSON.parse(
  readFileSync("tests/fixtures/qwen3-1.7b-conformance-goldens.json", "utf-8")
) as Record<string, number[]>;

function mockShow(bodyJson: string = VOCAB_JSON) {
  return vi.spyOn(globalThis, "fetch").mockResolvedValue(new Response(bodyJson, { status: 200 }));
}

beforeEach(() => {
  __resetVocabCacheForTests();
  vi.restoreAllMocks();
});

// ── AC-DEP-1 ──────────────────────────────────────────────────────────

describe("AC-DEP-1: vocab/merges come only from a live POST /show (verbose)", () => {
  it("posts verbose:true with the model name, reading model_info fields — not a bundled file", async () => {
    const fetchSpy = mockShow();
    await tokenize(BASE_URL, MODEL, "hi");

    expect(fetchSpy).toHaveBeenCalledTimes(1);
    const [url, init] = fetchSpy.mock.calls[0];
    expect(url).toBe(`${BASE_URL}/show`);
    // The whole request shape is the contract with Ollama, not just the
    // body: /show is a JSON POST. A request that omits the method or the
    // Content-Type is not a request this AC describes, even though a
    // permissive stub (or a permissive server) would still answer it.
    expect((init as RequestInit).method).toBe("POST");
    expect((init as RequestInit).headers).toEqual({ "Content-Type": "application/json" });
    const body = JSON.parse((init as RequestInit).body as string);
    expect(body).toEqual({ model: MODEL, verbose: true });
  });

  it("reflects a renamed special-token vocab entry in tokenize() output (not a mock-spy proxy)", async () => {
    const mutated = JSON.parse(VOCAB_JSON);
    const tokens: string[] = mutated.model_info["tokenizer.ggml.tokens"];
    const idx = tokens.indexOf("<|im_start|>");
    expect(idx).toBeGreaterThanOrEqual(0);
    tokens[idx] = "<|CUSTOM_START|>";
    mockShow(JSON.stringify(mutated));

    const result = await tokenize(BASE_URL, MODEL, "<|CUSTOM_START|>hi");
    // The mutation is observed in the ACTUAL returned tokens/tokenIds —
    // not merely confirmed by inspecting what fetch was called with.
    expect(result.tokens[0]).toBe("<|CUSTOM_START|>");
    expect(result.tokenIds[0]).toBe(idx);
  });

  it("reflects two swapped merge ranks in tokenize() output — genuinely observable, not order-irrelevant", async () => {
    // "abf" is deliberately ambiguous under the REAL qwen3:1.7b merge
    // table: (a,b) [rank 114] and (b,f) [rank 12977] are both candidate
    // merges in the SAME step, so swapping their relative priority
    // changes which one wins, producing a DIFFERENT final segmentation
    // ("ab","f" vs "a","bf"). Re-derived against the real, recaptured
    // vocab fixture — the original hand-built fixture used a deliberately
    // constructed "xyz" (x,y)/(y,z) pair that only existed in that fake
    // 297-token table; "abf" is this discriminator's real-vocab
    // replacement, found by searching the real merge table for a triple
    // with the same "one merge wins, the loser becomes a no-op" shape (a
    // two-token result on both sides, not a further-cascading merge to a
    // single token) and confirmed end-to-end against tokenize().
    mockShow();
    const before = await tokenize(BASE_URL, MODEL, "abf");
    expect(before.tokens).toEqual(["ab", "f"]);

    __resetVocabCacheForTests();
    const swapped = JSON.parse(VOCAB_JSON);
    const merges: string[] = swapped.model_info["tokenizer.ggml.merges"];
    const i1 = merges.indexOf("a b");
    const i2 = merges.indexOf("b f");
    expect(i1).toBeGreaterThanOrEqual(0);
    expect(i2).toBeGreaterThanOrEqual(0);
    [merges[i1], merges[i2]] = [merges[i2], merges[i1]];
    mockShow(JSON.stringify(swapped));

    const after = await tokenize(BASE_URL, MODEL, "abf");
    expect(after.tokens).toEqual(["a", "bf"]);
    expect(after.tokens).not.toEqual(before.tokens);
  });

  it("server/tokenizer.ts contains no textual reference to a committed fixture path and imports nothing from node:fs (grep-level guard for VQ-S3-002)", async () => {
    // This is a structural guard, not a behavioral one: if
    // server/tokenizer.ts imported the fixture file itself, the rest of
    // this suite's assertions would still pass technically (the fixture's
    // own real content would just be feeding itself). The two textual
    // checks below catch a `tests/fixtures/...` path or a `.json`-suffixed
    // literal; the `node:fs` import check catches a computed path or a
    // `.json.gz`-named one (S3-F10's rename made the old `.json` check
    // weaker on its own, since the real fixture is no longer `.json`-named
    // at all) that the textual checks would miss.
    const src = readFileSync("server/tokenizer.ts", "utf-8");
    expect(src).not.toMatch(/tests\/fixtures/);
    expect(src).not.toMatch(/\.json["']/);
    expect(src).not.toMatch(/from\s+["']node:fs["']/);
  });
});

// ── AC-TOK-1 (live-gated) ───────────────────────────────────────────

describe("AC-TOK-1 (live-gated): tokenize() length matches the raw-count oracle", () => {
  it("skips cleanly (never fails) when the live gate is closed; runs for real when open", async (ctx) => {
    const baseUrl = tokenizerLiveOllamaUrl();
    const gate = await checkLiveGate(baseUrl, MODEL);

    if (!gate.open) {
      // Dynamic skip (Vitest's ctx.skip()) — this must report as SKIPPED,
      // never as passed-with-no-assertions and never as failed. The
      // reason distinguishes host-unreachable from model-not-pulled
      // (AC-ERR-3).
      ctx.skip(`live gate closed: ${gate.reason}`);
      return;
    }

    for (const [index, text] of FIXTURE_SET.entries()) {
      // S3-C8/S3-D3: prepend a per-iteration nonce so no two prompts sent
      // in this loop share a common prefix. Ollama has, on some versions,
      // reported only the NON-cached portion of a prompt in
      // `prompt_eval_count` on a KV-cache prefix hit; six prompts sent to
      // the same model in sequence would otherwise risk that, making this
      // oracle under-count for reasons unrelated to the tokenizer under
      // test. The random component is placed FIRST (not after a shared
      // literal like "nonce-") so no two prompts share a leading token
      // either — a shared prefix token would still risk the same
      // cache-hit under-count this nonce exists to dodge. The nonce is
      // prepended to the SAME string passed to both `tokenize()` and the
      // oracle, so the two token counts still refer to identical text.
      // This is a defensive, unverified assumption — this test is always
      // skipped in this sandbox (no live Ollama host), so the fix has not
      // been exercised against a real build. If a live run of this test
      // starts failing on an under-count again, re-examine whether the
      // KV-cache-hit theory (rather than the nonce itself) is the real
      // cause before assuming the tokenizer regressed.
      //
      // Note: AC-TOK-1 is phrased over "every string in the fixture set"
      // tokenized on its own; prepending a nonce means each string is
      // actually checked IN CONTEXT (e.g. " strawberry" rather than
      // standalone "strawberry") rather than standalone. Both sides of
      // the comparison (tokenize() and the oracle) see the identical
      // nonce+text, so the comparison itself is still sound — this is a
      // deliberate, noted departure from the AC's literal per-string
      // phrasing, not an oversight.
      const nonce = `${Math.random().toString(36).slice(2)}-${index}-${Date.now()} `;
      const promptText = nonce + text;
      const result = await tokenize(baseUrl, MODEL, promptText);
      const oracleResponse = await fetch(`${baseUrl}/generate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          model: MODEL,
          prompt: promptText,
          raw: true,
          stream: false,
          options: { num_predict: 1 },
        }),
      });
      const oracleBody = (await oracleResponse.json()) as { prompt_eval_count?: number };
      expect(result.tokenIds.length).toBe(oracleBody.prompt_eval_count);
    }
  });
});

// ── AC-TOK-7 (fixture-backed): exact golden match ────────────────────

describe("AC-TOK-7: tokenize() matches the golden fixture exactly, element for element", () => {
  beforeEach(() => mockShow());

  // The parameterized loop below already discriminates a merge-table-free
  // (byte-split) implementation on its own, without a dedicated test
  // (VQ-S3-001): "strawberry" byte-encodes to 10 single-byte-alphabet
  // characters (s,t,r,a,w,b,e,r,r,y — all identity-mapped ASCII, so byte
  // length == char length here), so a byte-split/no-merge implementation
  // would emit 10 tokenIds, while the golden fixture's real,
  // merge-consulting segmentation is 3 ("st","raw","berry") — a mismatch
  // this loop's `toEqual(GOLDENS[text])` assertion for `"strawberry"`
  // already catches directly (S3-F7: the dedicated test below this
  // comment used to duplicate exactly this coverage).
  for (const text of FIXTURE_SET) {
    it(`matches the golden tokenIds for ${JSON.stringify(text)}`, async () => {
      const result = await tokenize(BASE_URL, MODEL, text);
      expect(result.tokenIds).toEqual(GOLDENS[text]);
    });
  }
});

// ── Reference-tokenizer conformance (fixture-backed) ─────────────────
//
// The genuine conformance suite this epic was missing: every case here
// exercises a class the original hand-built fixture could not, because
// that fixture's 297-token vocab and 37-line merge table were themselves
// constructed by hand rather than captured — digit-by-digit numeric
// splitting, special/control tokens matched verbatim ahead of BPE,
// contractions, U+0085 (NEL) and U+FEFF (BOM) at the Unicode-vs-\s
// boundary, emoji + CJK multi-byte sequences, and leading/embedded
// whitespace runs. `CONFORMANCE_GOLDENS` was produced by
// `@huggingface/transformers`' `AutoTokenizer.from_pretrained` against
// the real `Qwen/Qwen3-1.7B` tokenizer.json — an INDEPENDENT
// implementation of the same tokenizer this repo's `qwen3:1.7b` vocab
// fixture describes. Fixture-backed (not live-gated) deliberately: this
// gives regression protection on every hostless run rather than only
// when a live Ollama host happens to be reachable, and the golden values
// don't depend on one being reachable to have been produced correctly.
describe("Reference-tokenizer conformance: tokenize() matches @huggingface/transformers over the real vocab", () => {
  beforeEach(() => mockShow());

  for (const text of Object.keys(CONFORMANCE_GOLDENS)) {
    it(`matches the reference tokenizer's tokenIds for ${JSON.stringify(text)}`, async () => {
      const result = await tokenize(BASE_URL, MODEL, text);
      expect(result.tokenIds).toEqual(CONFORMANCE_GOLDENS[text]);
    });
  }
});

// ── AC-TOK-2 ──────────────────────────────────────────────────────────

describe("AC-TOK-2: tokens/tokenIds round-trip via the vocabulary", () => {
  beforeEach(() => mockShow());

  // A naive whole-string single-token split is not satisfiable by this
  // loop either, without a dedicated test (S3-F7 subsumption): such a
  // split would trivially round-trip (tokens=[s]) but fail the
  // vocab-index/byte-decode check below for any fixture-set string that
  // is not itself a single vocab entry — true for the fenced-code-block
  // and literal-pipe fixtures, which the per-index `decodeTokenIds` check
  // below already exercises.
  it.each(FIXTURE_SET)("holds for %s", async (text) => {
    const vocab = await loadVocab(BASE_URL, MODEL);
    const result = tokenizeWithVocab(vocab, text);

    expect(result.tokens).toHaveLength(result.tokenIds.length);
    expect(result.tokens.join("")).toBe(text);

    // tokenIds[i] must be the vocabulary index whose byte-level decoding
    // is tokens[i]. None of the fixture-set strings contain a multi-byte
    // character that a token boundary splits (they're all plain ASCII),
    // so decoding each id INDIVIDUALLY must reproduce tokens[i] exactly —
    // the same claim the streaming decoder makes for the whole sequence,
    // checked here per-index rather than only in aggregate.
    for (let i = 0; i < result.tokenIds.length; i++) {
      expect(decodeTokenIds(vocab, [result.tokenIds[i]])).toEqual([result.tokens[i]]);
    }
  });
});

// ── AC-TOK-3 ──────────────────────────────────────────────────────────

describe("AC-TOK-3: special tokens tokenize as exactly one element each", () => {
  beforeEach(() => mockShow());

  it("<|im_start|> and <|im_end|> each occupy exactly one tokens[] element with the correct id", async () => {
    const vocab = await loadVocab(BASE_URL, MODEL);
    const result = await tokenize(BASE_URL, MODEL, "<|im_start|>Hello<|im_end|>");

    const startIdx = result.tokens.indexOf("<|im_start|>");
    const endIdx = result.tokens.indexOf("<|im_end|>");
    expect(startIdx).toBe(0);
    expect(endIdx).toBe(result.tokens.length - 1);
    expect(result.tokenIds[startIdx]).toBe(vocab.tokenToId.get("<|im_start|>"));
    expect(result.tokenIds[endIdx]).toBe(vocab.tokenToId.get("<|im_end|>"));

    // Not merely "the substring appears somewhere in the joined output" —
    // each special token is its OWN array element, never split.
    expect(result.tokens.filter((t) => t === "<|im_start|>")).toHaveLength(1);
    expect(result.tokens.filter((t) => t === "<|im_end|>")).toHaveLength(1);
  });

  it("matches special tokens ahead of the pre-tokenizer split (adjacent to ordinary text, no separating space)", async () => {
    // If special-token matching ran AFTER the qwen2 split, the regex
    // would instead try to tokenize the literal characters
    // "<|im_start|>" as ordinary punctuation/letter runs.
    const result = await tokenize(BASE_URL, MODEL, "<|im_start|>a|b<|im_end|>");
    expect(result.tokens[0]).toBe("<|im_start|>");
    expect(result.tokens[result.tokens.length - 1]).toBe("<|im_end|>");
  });

  it("also recognizes token_type-classified control tokens that are NOT <|...|>-shaped (S3-C2)", async () => {
    // The fixture's tokenizer.ggml.token_type array marks "<think>" as
    // CONTROL (type 3), same as real Qwen3 GGUF vocabularies — it is not
    // `<|...|>`-shaped, so the shape-based fallback regex alone would
    // split it into ordinary BPE pieces instead of one element. This app
    // is a chat UI for a model that emits "<think>" literally, so this
    // is routine input, not an exotic edge case.
    const vocab = await loadVocab(BASE_URL, MODEL);
    const result = await tokenize(BASE_URL, MODEL, "<think>Hello</think>");

    expect(result.tokens[0]).toBe("<think>");
    expect(result.tokens[result.tokens.length - 1]).toBe("</think>");
    expect(result.tokenIds[0]).toBe(vocab.tokenToId.get("<think>"));
    expect(result.tokenIds[result.tokenIds.length - 1]).toBe(vocab.tokenToId.get("</think>"));
    expect(result.tokens.filter((t) => t === "<think>")).toHaveLength(1);
    expect(result.tokens.filter((t) => t === "</think>")).toHaveLength(1);
  });
});

// ── S3-D2 (fixture-independent): the token_type-absent fallback ─────

describe("S3-D2 (fixture-independent): shape-based special-token fallback when tokenizer.ggml.token_type is absent or malformed", () => {
  // The committed fixture always carries a correctly-sized token_type
  // array, so the AC-TOK-3 suite above only ever exercises the preferred
  // (token_type-driven) branch in buildVocabTable — the shape-regex
  // fallback that runs against any /show response omitting token_type
  // was otherwise untested. This is also the exact branch that
  // reinstates the shape-based detection S3-C2 replaced (that detection
  // was silently wrong for Qwen3's non-`<|...|>`-shaped control tokens),
  // so these tests pin precisely what it does and does not catch rather
  // than asserting it is equivalent to the preferred branch.

  it("still matches <|...|>-shaped tokens as single elements when token_type is absent entirely (the fallback's shape path works)", async () => {
    const mutated = JSON.parse(VOCAB_JSON);
    delete mutated.model_info["tokenizer.ggml.token_type"];
    mockShow(JSON.stringify(mutated));

    const result = await tokenize(BASE_URL, MODEL, "<|im_start|>Hello<|im_end|>");
    expect(result.tokens[0]).toBe("<|im_start|>");
    expect(result.tokens[result.tokens.length - 1]).toBe("<|im_end|>");
    expect(result.tokens.filter((t) => t === "<|im_start|>")).toHaveLength(1);
    expect(result.tokens.filter((t) => t === "<|im_end|>")).toHaveLength(1);
  });

  it("does NOT match a non-<|...|>-shaped control token like <think> when token_type is absent — the fallback's known limitation", async () => {
    const mutated = JSON.parse(VOCAB_JSON);
    delete mutated.model_info["tokenizer.ggml.token_type"];
    mockShow(JSON.stringify(mutated));

    const result = await tokenize(BASE_URL, MODEL, "<think>Hello</think>");
    // Unlike the token_type-driven branch (AC-TOK-3 above), the shape
    // regex only matches `<|...|>`, so "<think>" is run through the
    // ordinary pre-tokenizer/BPE path instead of being kept as one
    // element — this is the documented gap S3-C2 exists to close, and
    // the reason token_type is preferred whenever /show provides it.
    expect(result.tokens.filter((t) => t === "<think>")).toHaveLength(0);
    expect(result.tokens.filter((t) => t === "</think>")).toHaveLength(0);
  });

  it("falls back to shape-based detection when token_type's length doesn't match tokens' length, pinning the length guard", async () => {
    const mutated = JSON.parse(VOCAB_JSON);
    const tokenType: number[] = mutated.model_info["tokenizer.ggml.token_type"];
    // Deliberately truncated — one shorter than tokens[] — so the
    // `tokenType.length === tokens.length` guard in buildVocabTable
    // fails even though the array is present.
    mutated.model_info["tokenizer.ggml.token_type"] = tokenType.slice(0, -1);
    mockShow(JSON.stringify(mutated));

    const result = await tokenize(BASE_URL, MODEL, "<|im_start|>Hello<|im_end|>");
    expect(result.tokens[0]).toBe("<|im_start|>");
    expect(result.tokens[result.tokens.length - 1]).toBe("<|im_end|>");

    // The two assertions above hold under BOTH branches (a wrongly-sized
    // token_type array still classifies <|im_start|>/<|im_end|> as
    // CONTROL), so on their own they cannot tell whether the length guard
    // fired at all. "<think>" is the discriminator: it is CONTROL in the
    // array but not <|...|>-shaped, so it survives as one element only if
    // the array was trusted. A guard that accepted the mismatched array
    // would keep it whole here. (No cache reset: this reuses the very
    // table built above, so it cannot accidentally be answered by a
    // differently-built one.)
    const thinkResult = await tokenize(BASE_URL, MODEL, "<think>Hello</think>");
    expect(thinkResult.tokens.filter((t) => t === "<think>")).toHaveLength(0);
    expect(thinkResult.tokens.join("")).toBe("<think>Hello</think>");
  });
});

// ── S3-C1 (fixture-independent) ──────────────────────────────────────

describe("S3-C1 (fixture-independent): the real Qwen pre-tokenizer splits every digit into its own pre-token", () => {
  beforeEach(() => mockShow());

  // Deliberately does NOT go through GOLDENS/FIXTURE_SET: those fixtures
  // are hand-built using this same module's own helpers (see the file
  // header), so they cannot falsify anything about the pre-tokenizer
  // itself — a regression back to cl100k_base's `\p{N}{1,3}` digit rule
  // would still satisfy every golden, since none of them contain a
  // digit. This test instead constructs its own vocab mutation and
  // asserts on segmentation shape directly, so it fails against the
  // buggy regex regardless of what the committed fixture happens to say.
  it("never merges adjacent digits, even when the vocab's merge table would otherwise allow it", async () => {
    const mutated = JSON.parse(VOCAB_JSON);
    const tokens: string[] = mutated.model_info["tokenizer.ggml.tokens"];
    const merges: string[] = mutated.model_info["tokenizer.ggml.merges"];

    // "2" and "0" are identity-mapped ASCII in the GPT-2 byte alphabet
    // (byteEncode("2") === "2"), so if the pre-tokenizer ever produced a
    // pre-token containing both digits adjacently (e.g. cl100k_base's
    // `\p{N}{1,3}` grouping "20" into one pre-token), this merge rule
    // would fire and collapse them into a single "20" token. Under the
    // real Qwen `\p{N}` rule, "2" and "0" can never appear in the same
    // pre-token in the first place, so this merge must never have a
    // chance to apply — regardless of what any hand-built golden says.
    if (!tokens.includes("20")) tokens.push("20");
    merges.push("2 0");
    mockShow(JSON.stringify(mutated));

    const result = await tokenize(BASE_URL, MODEL, "2024");
    expect(result.tokens).toEqual(["2", "0", "2", "4"]);
  });
});

// ── S3-C6 / S3-C9 (pre-tokenizer boundary, direct) ───────────────────
//
// These exercise __preTokenizeForTests directly rather than through
// tokenize(): the BPE merge step re-splits every pre-token into
// byte-level symbols unless a merge rule happens to apply, which makes
// pre-token boundaries themselves unobservable through tokenize()'s
// public tokens[] output for arbitrary (non-fixture) input.

describe("S3-C6: case-insensitivity is scoped to the contraction group only", () => {
  it("does not simple-case-fold a combining mark into \\p{L}, unlike a whole-pattern /i flag would", () => {
    // U+0345 COMBINING GREEK YPOGEGRAMMENI case-folds to U+03B9 (ι), a
    // letter — so a whole-pattern `i` flag (with `u`) would make
    // `[^\r\n\p{L}\p{N}]?\p{L}+` treat the combining mark as `\p{L}` and
    // absorb it into the preceding letter run. Precomposed "ᾳ" (U+1FB3)
    // is itself `\p{L}` and stays whole either way; the decomposed form
    // (base letter + combining mark) is the case that discriminates.
    expect(__preTokenizeForTests("ᾳ b")).toEqual(["α", "ͅ", " b"]);
  });
});

describe("S3-C9: whitespace matches Unicode White_Space, not JS's \\s/\\S", () => {
  it("treats U+0085 (NEL) as whitespace, unlike JS's \\s (which excludes it)", () => {
    // JS's \s excludes U+0085 (Next Line); Unicode White_Space includes
    // it. Under \s, two adjacent NELs are ordinary "punctuation" and stay
    // together as one run, with the following letter run split off on
    // its own ("a", "\u0085\u0085", "d"). Under White_Space, the run is
    // whitespace, so the pattern's usual "leave the last space attached
    // to the next word" behavior applies instead ("a", "\u0085",
    // "\u0085d") — a different split, not just a different label.
    expect(__preTokenizeForTests("a\u0085\u0085d")).toEqual(["a", "\u0085", "\u0085d"]);
  });

  it("does not treat U+FEFF (BOM) as whitespace, unlike JS's \\s (which includes it)", () => {
    // Mirror image of the NEL case: JS's \s includes U+FEFF, so two
    // adjacent BOMs would be treated as a whitespace run and split as
    // ("a", "﻿", "﻿d"). Unicode White_Space excludes U+FEFF, so
    // it is ordinary "punctuation" instead and the run stays together:
    // ("a", "﻿﻿", "d").
    expect(__preTokenizeForTests("a﻿﻿d")).toEqual(["a", "﻿﻿", "d"]);
  });
});

// ── AC-PERF-1 / Order-Sensitive Composition Flow 1 ───────────────────

describe("AC-PERF-1: exactly one POST /show per (baseUrl, model), sequential and concurrent", () => {
  it("issues one request across two sequential calls", async () => {
    const fetchSpy = mockShow();
    await tokenize(BASE_URL, MODEL, "Hello world");
    await tokenize(BASE_URL, MODEL, "strawberry");
    expect(fetchSpy).toHaveBeenCalledTimes(1);
  });

  it("issues exactly one request for two calls started concurrently via Promise.all", async () => {
    let resolveShow!: (r: Response) => void;
    const fetchSpy = vi.spyOn(globalThis, "fetch").mockImplementation(
      () => new Promise<Response>((resolve) => { resolveShow = resolve; })
    );

    const p1 = tokenize(BASE_URL, MODEL, "Hello world");
    const p2 = tokenize(BASE_URL, MODEL, "strawberry");
    // Both calls started before the first /show resolves — a cache
    // populated only on resolution would issue two requests here.
    expect(fetchSpy).toHaveBeenCalledTimes(1);

    resolveShow(new Response(VOCAB_JSON, { status: 200 }));
    const [r1, r2] = await Promise.all([p1, p2]);

    expect(fetchSpy).toHaveBeenCalledTimes(1);
    expect(r1.tokenIds).toEqual(GOLDENS["Hello world"]);
    expect(r2.tokenIds).toEqual(GOLDENS["strawberry"]);
  });

  it("issues exactly one request for N=5 concurrent first-calls, and every caller resolves to the same vocab table", async () => {
    let resolveShow!: (r: Response) => void;
    const fetchSpy = vi.spyOn(globalThis, "fetch").mockImplementation(
      () => new Promise<Response>((resolve) => { resolveShow = resolve; })
    );

    const texts = ["Hello world", "strawberry", "Die Verkehrsinfrastruktur", "a|b", "a\n\n\nb"];
    const calls = texts.map((t) => tokenize(BASE_URL, MODEL, t));
    expect(fetchSpy).toHaveBeenCalledTimes(1);

    resolveShow(new Response(VOCAB_JSON, { status: 200 }));
    const results = await Promise.all(calls);

    expect(fetchSpy).toHaveBeenCalledTimes(1);
    results.forEach((r, i) => {
      expect(r.tokenIds).toEqual(GOLDENS[texts[i]]);
    });
  });

  it("a failed load is not cached — the next call retries the fetch", async () => {
    const fetchSpy = vi
      .spyOn(globalThis, "fetch")
      .mockRejectedValueOnce(new Error("network down"))
      .mockResolvedValueOnce(new Response(VOCAB_JSON, { status: 200 }));

    await expect(tokenize(BASE_URL, MODEL, "hi")).rejects.toThrow();
    const result = await tokenize(BASE_URL, MODEL, "Hello world");

    expect(fetchSpy).toHaveBeenCalledTimes(2);
    expect(result.tokenIds).toEqual(GOLDENS["Hello world"]);
  });

  it("never evicts an in-flight entry, even when the bounded LRU is exceeded (S3-R2)", async () => {
    const resolvers: Array<(r: Response) => void> = [];
    const fetchSpy = vi.spyOn(globalThis, "fetch").mockImplementation(
      () => new Promise<Response>((resolve) => { resolvers.push(resolve); })
    );

    const MODEL_A = "model-a";
    const MODEL_B = "model-b";
    const MODEL_C = "model-c";
    const MODEL_D = "model-d";

    // A and B are loaded and settle immediately — A is the oldest entry
    // once C and D are added below.
    const pA = loadVocab(BASE_URL, MODEL_A);
    resolvers[0](new Response(VOCAB_JSON, { status: 200 }));
    await pA;

    const pB = loadVocab(BASE_URL, MODEL_B);
    resolvers[1](new Response(VOCAB_JSON, { status: 200 }));
    await pB;

    // C is started but deliberately left in flight — its /show never
    // resolves until later in this test.
    const pC = loadVocab(BASE_URL, MODEL_C);
    expect(fetchSpy).toHaveBeenCalledTimes(3);

    // D pushes the cache to size 4 (> VOCAB_CACHE_MAX_ENTRIES=3),
    // triggering eviction. The naive "evict the oldest key" policy would
    // evict C here, even though it is still in flight (S3-R2). The fix
    // must instead evict A: the oldest entry that has actually SETTLED.
    const pD = loadVocab(BASE_URL, MODEL_D);
    resolvers[3](new Response(VOCAB_JSON, { status: 200 }));
    await pD;

    // Only now does C's original /show resolve.
    resolvers[2](new Response(VOCAB_JSON, { status: 200 }));
    await pC;

    // A second call for C must attach to the very entry that survived
    // eviction — no new /show — proving it was never dropped while in
    // flight.
    await loadVocab(BASE_URL, MODEL_C);
    expect(fetchSpy).toHaveBeenCalledTimes(4);

    // A, by contrast, was legitimately evicted (it had already settled),
    // so calling it again correctly issues a fresh /show.
    const pA2 = loadVocab(BASE_URL, MODEL_A);
    expect(fetchSpy).toHaveBeenCalledTimes(5);
    resolvers[4](new Response(VOCAB_JSON, { status: 200 }));
    await pA2;
  });
});

// ── AC-ERR-2 (vocab_unavailable half; unsupported_provider is ws-handler's) ──

describe("fails closed on an unsupported tokenizer.ggml.pre (AC-ERR-2's vocab_unavailable half)", () => {
  it("throws VocabUnavailableError, never falling back to a different split algorithm", async () => {
    const bad = JSON.parse(VOCAB_JSON);
    bad.model_info["tokenizer.ggml.pre"] = "llama3";
    mockShow(JSON.stringify(bad));

    await expect(tokenize(BASE_URL, "some-llama-model", "hi")).rejects.toThrow(VocabUnavailableError);
  });

  it("throws VocabUnavailableError when model_info is missing the tokenizer fields entirely", async () => {
    mockShow(JSON.stringify({ model_info: {} }));
    await expect(tokenize(BASE_URL, MODEL, "hi")).rejects.toThrow(VocabUnavailableError);
  });

  it("throws VocabUnavailableError when the host is unreachable", async () => {
    vi.spyOn(globalThis, "fetch").mockRejectedValue(new Error("ECONNREFUSED"));
    await expect(tokenize(BASE_URL, MODEL, "hi")).rejects.toThrow(VocabUnavailableError);
  });
});

// ── AC-TOK-6: property test over arbitrary well-formed unicode ───────

describe("AC-TOK-6: tokens.join('') === s for arbitrary well-formed unicode", () => {
  beforeEach(() => mockShow());

  it("holds for fc.string({unit: 'binary'}) — full Unicode scalar range, no lone surrogates", async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.string({ unit: "binary", maxLength: 60 }),
        async (s) => {
          const result = await tokenize(BASE_URL, MODEL, s);
          expect(result.tokens.join("")).toBe(s);
          expect(result.tokens).toHaveLength(result.tokenIds.length);
        }
      ),
      { numRuns: 300 }
    );
  });

  it("holds for the empty string and length-1 strings", async () => {
    const empty = await tokenize(BASE_URL, MODEL, "");
    expect(empty.tokens).toEqual([]);
    expect(empty.tokenIds).toEqual([]);

    for (const ch of ["a", " ", "\n", "😀", "|"]) {
      const result = await tokenize(BASE_URL, MODEL, ch);
      expect(result.tokens.join("")).toBe(ch);
    }
  });

  it("holds for a leading BOM (U+FEFF) — TextDecoder must not strip it", async () => {
    const s = "﻿hello";
    const result = await tokenize(BASE_URL, MODEL, s);
    expect(result.tokens.join("")).toBe(s);
  });

  it("holds for mixed scripts, emoji, and consecutive-whitespace runs", async () => {
    const samples = ["héllo wörld", "日本語テスト", "a😀😀b", "a     b", "line1\n\n\nline2", "\t\t  \n"];
    for (const s of samples) {
      const result = await tokenize(BASE_URL, MODEL, s);
      expect(result.tokens.join("")).toBe(s);
    }
  });
});

// ── Gate-remediation additions (mutation survivor closure) ──────────
//
// The pre-ship mutation gate scored server/tokenizer.ts at 0.671 (186
// killed / 74 survived / 17 no-coverage) and deliberately DEFERRED
// classification of every survivor rather than shipping on an unaudited
// list. The describe blocks below close the classified real gaps: direct
// `bpeMerge` unit tests (it is exported specifically to be testable this
// way, but had zero direct coverage before this pass -- only indirect
// exercise through real vocab data, which never produces the tie/
// collision/mismatch shapes constructed here), special-token matching
// edge cases, and the LRU's recency/boundary/identity-guard invariants.

describe("bpeMerge (direct): rank selection, tie-breaking, and matching precision", () => {
  it("merges the lowest-rank adjacent pair first, not the first-found or a higher-rank one", () => {
    // (b,c) has the lower (better) rank even though (a,b) is encountered
    // first in word order -- the selection must scan for the true minimum
    // rank across ALL current pairs, not just take the first ranked one.
    const mergeRank = new Map([
      ["a\u0000b", 5],
      ["b\u0000c", 1],
    ]);
    expect(bpeMerge(["a", "b", "c"], mergeRank)).toEqual(["a", "bc"]);
  });

  it("resolves an equal-rank tie deterministically: the leftmost pair in word order wins", () => {
    // (a,b) and (b,c) overlap (share "b") and are deliberately given the
    // SAME rank -- only one can win this round. Insertion order into the
    // `pairs` map follows word position, so a correct strict "<" comparison
    // keeps the first-inserted (leftmost) entry; a "<=" bug would let the
    // later-inserted (b,c) overwrite it instead, producing ["a","bc"].
    const mergeRank = new Map([
      ["a\u0000b", 0],
      ["b\u0000c", 0],
    ]);
    expect(bpeMerge(["a", "b", "c"], mergeRank)).toEqual(["ab", "c"]);
  });

  it("PAIR_SEP prevents two differently-split adjacent pairs from colliding on the same map key", () => {
    // Without a separator between the pair's two components, position 0
    // ("ab","c" -> "ab"+"c") and position 2 ("a","bc" -> "a"+"bc") would
    // both stringify to the literal key "abc", silently colliding in the
    // `pairs` map and losing the position-0 entry. mergeRank here only
    // ranks the position-2 pair (correctly keyed "a\u0000bc"), so a
    // collision would leave nothing matched at all.
    const mergeRank = new Map([["a\u0000bc", 0]]);
    expect(bpeMerge(["ab", "c", "a", "bc"], mergeRank)).toEqual(["ab", "c", "abc"]);
  });

  it("does not merge a repeated `first` occurrence that isn't actually followed by `second`", () => {
    // word[0] is "a" (matches `first`) but is followed by another "a", not
    // "b" -- must NOT merge into a fabricated "ab" at that position. Only
    // the real (a,b) pair at position 1 may merge.
    const mergeRank = new Map([["a\u0000b", 0]]);
    expect(bpeMerge(["a", "a", "b"], mergeRank)).toEqual(["a", "ab"]);
  });

  it("returns the word unchanged when no pair in it has a rank (loop terminates without over- or under-merging)", () => {
    expect(bpeMerge(["p", "q", "r"], new Map())).toEqual(["p", "q", "r"]);
  });

  it("skips a malformed (single-word, no space) merges line without polluting mergeRank with a bogus entry", async () => {
    const mutated = JSON.parse(VOCAB_JSON);
    const merges: string[] = mutated.model_info["tokenizer.ggml.merges"];
    const originalCount = merges.length;
    merges.push("onlyoneword");
    mockShow(JSON.stringify(mutated));

    const vocab = await loadVocab(BASE_URL, MODEL);
    expect(vocab.mergeRank.size).toBe(originalCount);
    expect(vocab.mergeRank.has("onlyoneword\u0000undefined")).toBe(false);
  });
});

describe("special-token matching: longest-match, vocab-membership, and malformed VocabTable guards", () => {
  beforeEach(() => mockShow());

  it("longest-match wins when one special token is a literal prefix of another", async () => {
    const mutated = JSON.parse(VOCAB_JSON);
    const tokens: string[] = mutated.model_info["tokenizer.ggml.tokens"];
    const tokenType: number[] = mutated.model_info["tokenizer.ggml.token_type"];
    tokens.push("<|a|>");
    tokenType.push(3); // CONTROL
    const longId = tokens.length;
    tokens.push("<|a|>x");
    tokenType.push(3);
    mockShow(JSON.stringify(mutated));

    const result = await tokenize(BASE_URL, MODEL, "<|a|>x");
    // If the shorter "<|a|>" were matched first (unsorted/no-sort bug), this
    // would split into two elements instead of the one longest match.
    expect(result.tokens).toEqual(["<|a|>x"]);
    expect(result.tokenIds).toEqual([longId]);
  });

  it("a <|...|>-shaped string absent from the vocab's special tokens is tokenized as ordinary text, not matched verbatim", async () => {
    const result = await tokenize(BASE_URL, MODEL, "<|not_a_real_special_token|>");
    expect(result.tokens).not.toContain("<|not_a_real_special_token|>");
    expect(result.tokens.length).toBeGreaterThan(1);
    expect(result.tokens.join("")).toBe("<|not_a_real_special_token|>");
  });

  it("tokenizeWithVocab throws when specialTokenSet names a string absent from tokenToId (malformed VocabTable)", () => {
    const fakeVocab: VocabTable = {
      tokens: ["a"],
      tokenToId: new Map([["a", 0]]),
      mergeRank: new Map(),
      pre: "qwen2",
      specialTokens: ["<|fake|>"],
      specialTokenSet: new Set(["<|fake|>"]),
    };
    expect(() => tokenizeWithVocab(fakeVocab, "<|fake|>")).toThrow(
      /special token missing from vocab\.tokenToId/
    );
  });

  it("tokenizeWithVocab throws when BPE produces a symbol absent from the vocabulary", () => {
    const emptyVocab: VocabTable = {
      tokens: [],
      tokenToId: new Map(),
      mergeRank: new Map(),
      pre: "qwen2",
      specialTokens: [],
      specialTokenSet: new Set(),
    };
    expect(() => tokenizeWithVocab(emptyVocab, "x")).toThrow(
      /BPE produced a symbol absent from the vocabulary/
    );
  });

  it("decodeTokenIds throws for a vocab entry containing a character outside the byte alphabet", () => {
    const corruptVocab: VocabTable = {
      tokens: ["😀"],
      tokenToId: new Map([["😀", 0]]),
      mergeRank: new Map(),
      pre: "qwen2",
      specialTokens: [],
      specialTokenSet: new Set(),
    };
    expect(() => decodeTokenIds(corruptVocab, [0])).toThrow(
      /byte-decode: character not in the byte alphabet/
    );
  });

  it("__preTokenizeForTests('') returns [] (the empty-input guard, unreachable via tokenize() itself since upstream special-token splitting already filters out empty segments)", () => {
    expect(__preTokenizeForTests("")).toEqual([]);
  });
});

describe("LRU: capacity boundary, recency promotion (not insertion order), and identity-guarded cleanup", () => {
  it("loading exactly VOCAB_CACHE_MAX_ENTRIES (3) distinct keys causes zero eviction", async () => {
    // Each loadVocab call here fetches for a DIFFERENT key, so (unlike
    // mockShow's single shared Response) fetch must produce a fresh
    // Response per call -- a Response body can only be read once.
    const fetchSpy = vi
      .spyOn(globalThis, "fetch")
      .mockImplementation(async () => new Response(VOCAB_JSON, { status: 200 }));
    await loadVocab(BASE_URL, "model-x");
    await loadVocab(BASE_URL, "model-y");
    await loadVocab(BASE_URL, "model-z");

    // All three remain cached -- reloading any of them attaches without a
    // new fetch, proving none was prematurely evicted merely for sitting
    // exactly at (not over) capacity.
    await loadVocab(BASE_URL, "model-x");
    await loadVocab(BASE_URL, "model-y");
    await loadVocab(BASE_URL, "model-z");
    expect(fetchSpy).toHaveBeenCalledTimes(3);
  });

  it("evicts by recency, not insertion order: re-touching the oldest entry protects it from eviction", async () => {
    const fetchSpy = vi
      .spyOn(globalThis, "fetch")
      .mockImplementation(async () => new Response(VOCAB_JSON, { status: 200 }));
    await loadVocab(BASE_URL, "model-a"); // oldest by insertion
    await loadVocab(BASE_URL, "model-b");
    await loadVocab(BASE_URL, "model-c");
    expect(fetchSpy).toHaveBeenCalledTimes(3);

    // Touching "a" again promotes it to most-recently-used. Under a naive
    // insertion-order LRU (ignoring recency), "a" would still be the next
    // eviction target regardless of this touch.
    await loadVocab(BASE_URL, "model-a");
    expect(fetchSpy).toHaveBeenCalledTimes(3);

    // A 4th distinct key exceeds capacity; recency-based eviction must now
    // target "b" (now the least-recently-used), not "a".
    await loadVocab(BASE_URL, "model-d");
    expect(fetchSpy).toHaveBeenCalledTimes(4);

    // "a" survived eviction -> attaching to it issues no new fetch.
    await loadVocab(BASE_URL, "model-a");
    expect(fetchSpy).toHaveBeenCalledTimes(4);

    // "b" was the one actually evicted -> reloading it issues a fresh fetch.
    await loadVocab(BASE_URL, "model-b");
    expect(fetchSpy).toHaveBeenCalledTimes(5);
  });

  it("a stale rejection's cleanup never deletes a newer promise registered under the same key (identity guard, S3-R2)", async () => {
    let rejectFirst!: (e: unknown) => void;
    const fetchSpy = vi.spyOn(globalThis, "fetch").mockImplementationOnce(
      () => new Promise((_resolve, reject) => { rejectFirst = reject; })
    );

    const p1 = loadVocab(BASE_URL, MODEL); // in flight, will reject later
    p1.catch(() => {}); // this handle is deliberately abandoned below

    // Simulate the cache being cleared and a NEW promise registered under
    // the identical key BEFORE the first promise's rejection cleanup runs.
    __resetVocabCacheForTests();
    fetchSpy.mockResolvedValueOnce(new Response(VOCAB_JSON, { status: 200 }));
    const p2 = loadVocab(BASE_URL, MODEL);

    rejectFirst(new Error("stale failure"));
    await expect(p1).rejects.toThrow();
    await p2;

    // If the identity guard were broken (deleting by key alone), p1's
    // cleanup would have deleted p2's live entry too, forcing an
    // unnecessary third fetch here.
    await loadVocab(BASE_URL, MODEL);
    expect(fetchSpy).toHaveBeenCalledTimes(2);
  });
});

describe("fetchVocab: response-shape validation not exercised by the existing malformed-model_info suite", () => {
  it("throws VocabUnavailableError on a non-ok HTTP status, not just on a malformed 200 body", async () => {
    vi.spyOn(globalThis, "fetch").mockResolvedValue(new Response("server error", { status: 500 }));
    await expect(tokenize(BASE_URL, MODEL, "hi")).rejects.toThrow(VocabUnavailableError);
  });

  it("throws VocabUnavailableError (not a raw TypeError) when model_info is absent from the response body entirely", async () => {
    mockShow(JSON.stringify({}));
    await expect(tokenize(BASE_URL, MODEL, "hi")).rejects.toThrow(VocabUnavailableError);
  });
});

// ── Second gate-remediation pass (mutation survivor closure, round 2) ──
//
// The first remediation pass lifted server/tokenizer.ts from 0.671 to
// 0.799, leaving a survivor set whose real gaps all share one shape: a
// test asserts an outcome that BOTH the correct branch and the mutated
// branch produce, so the branch itself is never pinned. Each block below
// adds the discriminating assertion rather than a second test of the
// same outcome.

describe("AC-TOK-3: special-token detection matches a vocab entry's whole text, never a substring of it", () => {
  // Reachable only through the shape-based fallback (token_type absent),
  // which is the one detector that inspects an entry's TEXT rather than
  // the model's own classification. A vocabulary legitimately contains
  // ordinary entries that begin or end with the control-token
  // delimiters; treating one of those as a control token would make a
  // chat transcript's ordinary text silently un-splittable, and would
  // hand the boundary view a token the model never emits as one unit.
  it("does not treat a vocab entry that merely starts or ends with the <|...|> delimiters as a special token", async () => {
    const mutated = JSON.parse(VOCAB_JSON);
    const tokens: string[] = mutated.model_info["tokenizer.ggml.tokens"];
    delete mutated.model_info["tokenizer.ggml.token_type"];
    // "pre<|q|>" ends with the closing delimiter but does not start with
    // the opening one; "<|q|>post" is its mirror image. Only an entry
    // that is EXACTLY <|...|>-shaped may be matched verbatim.
    tokens.push("pre<|q|>");
    tokens.push("<|q|>post");
    mockShow(JSON.stringify(mutated));

    for (const text of ["pre<|q|>", "<|q|>post"]) {
      __resetVocabCacheForTests();
      mockShow(JSON.stringify(mutated));
      const result = await tokenize(BASE_URL, MODEL, text);
      expect(result.tokens.filter((t) => t === text)).toHaveLength(0);
      expect(result.tokens.length).toBeGreaterThan(1);
      expect(result.tokens.join("")).toBe(text);
    }
  });
});

describe("AC-TOK-7: tokenizing ordinary text does not depend on the vocabulary declaring any special tokens", () => {
  it("produces the golden segmentation for a vocabulary whose entries are all ordinary", async () => {
    // A vocabulary with zero special tokens is a legitimate shape (a base
    // model with no chat-control vocabulary), and ordinary text must
    // tokenize identically in it. Serving the real fixture with every
    // entry reclassified NORMAL isolates the "no special tokens at all"
    // path, which every other test in this suite skips past because the
    // fixture always declares control tokens.
    const mutated = JSON.parse(VOCAB_JSON);
    const tokens: string[] = mutated.model_info["tokenizer.ggml.tokens"];
    mutated.model_info["tokenizer.ggml.token_type"] = new Array(tokens.length).fill(1);
    mockShow(JSON.stringify(mutated));

    const result = await tokenize(BASE_URL, MODEL, "Hello world");
    expect(result.tokenIds).toEqual(GOLDENS["Hello world"]);
    expect(result.tokens.join("")).toBe("Hello world");
  });
});

describe("AC-TOK-7: bpeMerge only ever merges two symbols that are genuinely adjacent within the word", () => {
  it("ignores a merge rule whose pair would have to run past the end of the word", () => {
    // A merge table is data from the model, so nothing stops it from
    // containing a rule this word cannot satisfy. Ranking a pair whose
    // second half sits beyond the final symbol must not fabricate a
    // merge -- the pair simply does not occur in this word.
    const mergeRank = new Map([
      ["b\u0000undefined", 0],
      ["undefined\u0000undefined", 1],
    ]);
    expect(bpeMerge(["a", "b"], mergeRank)).toEqual(["a", "b"]);
  });
});

describe("AC-PERF-1: the one-request-per-(baseUrl, model) guarantee survives eviction in any recency order", () => {
  it("evicts a settled entry even when the least-recently-used entry is the one still in flight", async () => {
    // Mirror image of the existing S3-R2 test, which loads its settled
    // entries FIRST -- there, "evict the oldest" and "evict the oldest
    // SETTLED one" happen to name the same entry, so that test cannot
    // tell them apart. Here the in-flight entry is the oldest, so a
    // policy that evicts the first candidate it walks past would drop it
    // and a later caller for that model would race a second /show,
    // breaking AC-PERF-1 for that pair.
    const resolvers: Array<(r: Response) => void> = [];
    const fetchSpy = vi.spyOn(globalThis, "fetch").mockImplementation(
      () => new Promise<Response>((resolve) => { resolvers.push(resolve); })
    );

    // Oldest entry, deliberately left in flight for the whole test.
    const pStuck = loadVocab(BASE_URL, "model-stuck");

    const pA = loadVocab(BASE_URL, "model-a");
    resolvers[1](new Response(VOCAB_JSON, { status: 200 }));
    await pA;

    const pB = loadVocab(BASE_URL, "model-b");
    resolvers[2](new Response(VOCAB_JSON, { status: 200 }));
    await pB;

    // Fourth key exceeds the cap and forces an eviction.
    const pC = loadVocab(BASE_URL, "model-c");
    resolvers[3](new Response(VOCAB_JSON, { status: 200 }));
    await pC;
    expect(fetchSpy).toHaveBeenCalledTimes(4);

    // The in-flight entry must have survived: its caller attaches to the
    // same promise, with no second request for that model.
    const pStuckAgain = loadVocab(BASE_URL, "model-stuck");
    expect(fetchSpy).toHaveBeenCalledTimes(4);
    resolvers[0](new Response(VOCAB_JSON, { status: 200 }));
    expect(await pStuckAgain).toBe(await pStuck);

    // "model-a" was the settled entry that got evicted in its place.
    const pA2 = loadVocab(BASE_URL, "model-a");
    expect(fetchSpy).toHaveBeenCalledTimes(5);
    resolvers[4](new Response(VOCAB_JSON, { status: 200 }));
    await pA2;
  });
});

describe("AC-ERR-2: each way a /show response can be unusable is reported distinguishably", () => {
  // Every case here previously asserted only `rejects.toThrow(
  // VocabUnavailableError)`. That assertion is satisfied by ANY of the
  // module's failure paths, so a response missing only `merges` could be
  // reported as "unsupported pre" -- or the missing-fields check could be
  // deleted outright and the unsupported-pre check would still produce a
  // VocabUnavailableError, passing the test while telling the operator
  // the wrong thing. AC-ERR-2 is about a caller being able to act on the
  // reason, so the reason text is part of the contract.

  it("names the error class on the error itself, so a consumer matching on .name behaves like one matching on instanceof", async () => {
    vi.spyOn(globalThis, "fetch").mockRejectedValue(new Error("ECONNREFUSED"));
    await expect(tokenize(BASE_URL, MODEL, "hi")).rejects.toMatchObject({
      name: "VocabUnavailableError",
    });
  });

  it("reports an unreachable host as a failed request, quoting the model and the underlying cause", async () => {
    vi.spyOn(globalThis, "fetch").mockRejectedValue(new Error("ECONNREFUSED"));
    await expect(tokenize(BASE_URL, MODEL, "hi")).rejects.toThrow(
      /\/show request failed for model "qwen3:1\.7b".*ECONNREFUSED/
    );
  });

  it("reports a non-ok HTTP status as such, quoting the status code rather than the body", async () => {
    vi.spyOn(globalThis, "fetch").mockResolvedValue(new Response("server error", { status: 503 }));
    await expect(tokenize(BASE_URL, MODEL, "hi")).rejects.toThrow(
      /\/show failed for model "qwen3:1\.7b": 503/
    );
  });

  it.each([
    ["tokenizer.ggml.tokens"],
    ["tokenizer.ggml.merges"],
    ["tokenizer.ggml.pre"],
  ])("reports a response missing only %s as a missing-field failure, not as an unsupported pre-tokenizer", async (field) => {
    const mutated = JSON.parse(VOCAB_JSON);
    delete mutated.model_info[field];
    mockShow(JSON.stringify(mutated));

    await expect(tokenize(BASE_URL, MODEL, "hi")).rejects.toThrow(
      /is missing tokenizer\.ggml\.tokens\/merges\/pre in model_info/
    );
  });

  it("reports a pre-tokenizer this module does not implement by naming the value it got and the one it supports", async () => {
    const bad = JSON.parse(VOCAB_JSON);
    bad.model_info["tokenizer.ggml.pre"] = "llama3";
    mockShow(JSON.stringify(bad));

    await expect(tokenize(BASE_URL, "some-llama-model", "hi")).rejects.toThrow(
      /Unsupported tokenizer\.ggml\.pre "llama3" for model "some-llama-model" — only "qwen2" is implemented/
    );
  });
});

// ── Residual survivors after this pass: all EQUIVALENT, do not chase ──
//
// server/tokenizer.ts scores 258/298 (235 killed + 23 timeout) with 40
// live mutants, and every one of them is equivalent rather than an
// assertion gap. Recorded here so the next audit does not re-derive it:
//
//   * buildByteToUnicode()/BYTE_TO_UNICODE/UNICODE_TO_BYTE (15 mutants,
//     L42-L68) are STATIC: Stryker's own report flags them `static:
//     true`. The vitest runner imports the module once and activates
//     mutants per test afterwards, so a module-level initializer's
//     mutants never actually run -- including `BlockStatement -> {}` on
//     the builder, which would make the import throw. No test can kill
//     these; only `ignoreStatic: true` removes them from the score.
//   * The redundant halves of defensive guards: `preTokenize`'s
//     empty-string early return (`"".match(re) ?? []` is already `[]`),
//     `bpeMerge`'s `pairs.size === 0` and `word.length === 1` early
//     exits (the loop terminates identically without them), its
//     `rank !== undefined` conjunct (`undefined < Infinity` is false
//     anyway), the `i < word.length - 1` conjunct at the merge site (the
//     `word[i + 1] === second` check already implies it), the
//     merges-line `first === undefined` disjunct (`split(" ")` always
//     yields a first element), and the LRU's self-key skip (the touched
//     key is re-inserted last, so it is never reached first).
//   * `splitOnSpecialTokens`' empty-segment filter: an empty segment
//     produces no tokens either way.
//   * `decodeTokens`' trailing-flush block: the bytes fed to the
//     streaming decoder are, by construction, a complete UTF-8
//     sequence, so the final `decode()` is always empty.
